### ISSUE TITLE
Create avalanche problem forecasts

### ISSUE THREAD

**Issue by scottcha** [scottcha/OpenAvalancheProject#20]

**Comment by mkrueger12** [comment]
What are you looking for here?

**Comment by scottcha** [comment]
Basically this task is covering creating the ML models for each avy probelem type, such as Wind Slab, Deep Persistent Slab, . . ..

**Comment by mkrueger12** [comment]
Gotchya. Need any help collecting/cleaning data?

**Comment by LoganParker** [comment]
> Basically this task is covering creating the ML models for each avy probelem type, such as Wind Slab, Deep Persistent Slab, . . ..

What model do you have in mind for this task?

**Comment by scottcha** [comment]
I did take a stab at this awhile ago and at that time the ability to generate this was hampered by lack of data.  I've recently greatly expanded the amount of available data.  Most of the model's I've been spending my time on for the avalanche danger forecast have been dl models using the InceptionTime architecture.  I'll try and post the latest in a notebook.  This task is likely doing something similar for the problem types.

**Comment by LoganParker** [comment]
Let me know when you've got an updated notebook and I'll try to take a stab at it!
